name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.3.4

dependencies:
  cached_network_image:
  carousel_slider_plus:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_slidable:
  auto_size_text:
  colornames:
  flutter_svg:
  flutter_native_splash:
  readmore:
  smooth_page_indicator: ^2.0.1
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  get_it: ^9.2.0
  injectable: ^2.7.1+2

dev_dependencies:
  injectable_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints:

dependency_overrides:
  vector_math: ^2.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/



  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-.ttf



